---
language: python
python: "2.7"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt

before_script: "pep8 --ignore=E501,E402 --show-source --count ."

script: "python setup.py test"
